#!/usr/bin/env python3
"""
Hardware Health Monitor Module for Calamares
Configures comprehensive hardware monitoring
"""

import os
import sys
import json
import subprocess
import libcalamares
from pathlib import Path

sys.path.append(os.path.dirname(__file__))
from hardware_health_gui import HardwareHealthWidget

def pretty_name():
    return "Hardware Monitoring"

def icon():
    return "utilities-system-monitor"

def run():
    """Configure hardware monitoring"""
    gs = libcalamares.globalstorage
    health_config = gs.value("hardwareHealthConfig")
    
    if not health_config:
        health_config = get_default_config()
    
    # Apply hardware monitoring configuration
    try:
        apply_health_config(health_config)
        return None
    except Exception as e:
        return "Hardware monitoring setup failed", str(e)

def get_default_config():
    """Get default monitoring configuration"""
    return {
        "monitoring": {
            "temperature": True,
            "smart": True,
            "raid": True,
            "power": True
        },
        "alerts": {
            "email": "",
            "cpu_temp_warning": 75,
            "cpu_temp_critical": 85,
            "disk_temp_warning": 50,
            "disk_space_warning": 80
        },
        "services": [
            "lm-sensors",
            "smartmontools",
            "ipmitool"
        ]
    }

def apply_health_config(config):
    """Apply hardware monitoring configuration"""
    root_mount_point = libcalamares.globalstorage.value("rootMountPoint")
    
    # Configure smartd
    if config["monitoring"].get("smart"):
        configure_smartd(root_mount_point, config)
    
    # Configure lm-sensors
    if config["monitoring"].get("temperature"):
        configure_sensors(root_mount_point, config)
    
    # Configure IPMI if available
    if config["monitoring"].get("power"):
        configure_ipmi(root_mount_point, config)
    
    # Setup monitoring scripts
    setup_monitoring_scripts(root_mount_point, config)

def configure_smartd(root_path, config):
    """Configure SMART monitoring"""
    smartd_conf = """# smartd.conf - SMART monitoring configuration
# Generated by Z-FORGE installer

# Monitor all disks
DEVICESCAN -a -o on -S on -n standby,q -s (S/../.././02|L/../../6/03) -W 4,{},{}
""".format(
        config["alerts"]["disk_temp_warning"],
        config["alerts"]["disk_temp_warning"] + 10
    )
    
    if config["alerts"].get("email"):
        smartd_conf = smartd_conf.replace("DEVICESCAN", f"DEVICESCAN -m {config['alerts']['email']}")
    
    smartd_path = Path(root_path) / "etc/smartd.conf"
    smartd_path.parent.mkdir(parents=True, exist_ok=True)
    smartd_path.write_text(smartd_conf)

def configure_sensors(root_path, config):
    """Configure lm-sensors"""
    # Create sensors configuration
    sensors_conf = """# Sensor alarm thresholds
# Generated by Z-FORGE installer

chip "*-isa-*"
    label temp1 "CPU Temp"
    set temp1_max {}
    set temp1_crit {}
""".format(
        config["alerts"]["cpu_temp_warning"],
        config["alerts"]["cpu_temp_critical"]
    )
    
    sensors_path = Path(root_path) / "etc/sensors3.conf"
    sensors_path.parent.mkdir(parents=True, exist_ok=True)
    sensors_path.write_text(sensors_conf)

def configure_ipmi(root_path, config):
    """Configure IPMI monitoring"""
    ipmi_script = """#!/bin/bash
# IPMI monitoring script
# Generated by Z-FORGE installer

# Check if IPMI is available
if ! lsmod | grep -q ipmi; then
    modprobe ipmi_devintf
    modprobe ipmi_si
fi

# Monitor temperatures
ipmitool sdr type temperature | while read line; do
    temp=$(echo $line | awk '{print $10}')
    if [ "$temp" -gt "{}" ]; then
        logger -t ipmi-monitor "High temperature detected: $line"
    fi
done

# Monitor power supplies
ipmitool sdr type "Power Supply" | while read line; do
    if echo "$line" | grep -q "Failure"; then
        logger -t ipmi-monitor "Power supply issue: $line"
    fi
done
""".format(config["alerts"]["cpu_temp_warning"])
    
    script_path = Path(root_path) / "usr/local/bin/ipmi-monitor.sh"
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text(ipmi_script)
    script_path.chmod(0o755)

def setup_monitoring_scripts(root_path, config):
    """Setup monitoring and alerting scripts"""
    monitor_script = """#!/bin/bash
# Hardware monitoring script
# Generated by Z-FORGE installer

ALERT_EMAIL="{}"
CPU_WARN={}
CPU_CRIT={}
DISK_WARN={}

# Check CPU temperature
check_cpu_temp() {{
    sensors | grep "Core" | while read line; do
        temp=$(echo $line | grep -oP '\+\K[0-9]+' | head -1)
        if [ "$temp" -gt "$CPU_CRIT" ]; then
            echo "CRITICAL: CPU temperature $temp°C" | mail -s "Hardware Alert" $ALERT_EMAIL
        elif [ "$temp" -gt "$CPU_WARN" ]; then
            echo "WARNING: CPU temperature $temp°C" | logger -t hw-monitor
        fi
    done
}}

# Check disk space
check_disk_space() {{
    df -h | grep -vE '^Filesystem|tmpfs|cdrom|udev' | awk '{{print $5 " " $1}}' | while read output; do
        usage=$(echo $output | awk '{{print $1}}' | sed 's/%//g')
        partition=$(echo $output | awk '{{print $2}}')
        if [ "$usage" -gt "$DISK_WARN" ]; then
            echo "WARNING: Disk usage on $partition is ${{usage}}%" | logger -t hw-monitor
        fi
    done
}}

# Check RAID status
check_raid_status() {{
    if command -v megacli &> /dev/null; then
        megacli -LDInfo -Lall -aAll | grep "State" | grep -v "Optimal" && echo "RAID issue detected" | logger -t hw-monitor
    fi
}}

# Run checks
check_cpu_temp
check_disk_space
check_raid_status
""".format(
        config["alerts"].get("email", "root"),
        config["alerts"]["cpu_temp_warning"],
        config["alerts"]["cpu_temp_critical"],
        config["alerts"]["disk_space_warning"]
    )
    
    script_path = Path(root_path) / "usr/local/bin/hardware-monitor.sh"
    script_path.write_text(monitor_script)
    script_path.chmod(0o755)
    
    # Create cron job
    cron_content = """# Hardware monitoring cron job
*/5 * * * * root /usr/local/bin/hardware-monitor.sh
0 */6 * * * root /usr/local/bin/ipmi-monitor.sh
"""
    cron_path = Path(root_path) / "etc/cron.d/hardware-monitoring"
    cron_path.write_text(cron_content)

class HardwareHealthViewStep:
    """Calamares ViewStep for hardware health monitoring"""
    
    def __init__(self):
        self.widget = None
        self.gs = libcalamares.globalstorage
    
    def name(self):
        return "hardwarehealth"
    
    def pretty_name(self):
        return "Hardware Monitoring"
    
    def icon(self):
        return "utilities-system-monitor"
    
    def widget(self):
        if self.widget is None:
            self.widget = HardwareHealthWidget(self.gs)
        return self.widget
    
    def next(self):
        if self.widget:
            config = self.widget.get_configuration()
            self.gs.insert("hardwareHealthConfig", config)
        return None
    
    def back(self):
        return None
    
    def jobs(self):
        return []

calamares_module = HardwareHealthViewStep
