#!/bin/bash
# Build ZFS 2.3.3 Debian packages with P-core optimizations

set -e

# Version configuration
ZFS_VERSION="2.3.3"
BUILD_DIR="/usr/src/zfs-build"
ZFS_SOURCE_DIR="${BUILD_DIR}/zfs-${ZFS_VERSION}"

# Optimization flags for Meteor Lake - P-core aware
export CFLAGS="-O2 -march=native -mtune=native -pipe"
export CXXFLAGS="${CFLAGS}"
export LDFLAGS="-Wl,-O1 -Wl,--as-needed"

# Use P-cores for building
export DEB_BUILD_OPTIONS="parallel=8"

echo "=== Building ZFS ${ZFS_VERSION} Debian Packages ==="
echo "Build flags: ${CFLAGS}"

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo "Please run with sudo"
    exit 1
fi

# Install build dependencies
echo "Installing build dependencies..."
apt update
apt install -y \
    build-essential \
    debhelper \
    devscripts \
    dh-python \
    dh-dkms \
    autoconf \
    automake \
    libtool \
    gawk \
    dkms \
    libblkid-dev \
    uuid-dev \
    libudev-dev \
    libssl-dev \
    zlib1g-dev \
    libaio-dev \
    libattr1-dev \
    libelf-dev \
    linux-headers-$(uname -r) \
    python3-all-dev \
    python3-cffi \
    libffi-dev \
    python3-setuptools \
    python3-packaging \
    libcurl4-openssl-dev \
    po-debconf

# Create clean build directory
echo "Creating build directory..."
rm -rf ${BUILD_DIR}
mkdir -p ${BUILD_DIR}
cd ${BUILD_DIR}

# Download ZFS source
echo "Downloading ZFS ${ZFS_VERSION} source..."
wget -c https://github.com/openzfs/zfs/releases/download/zfs-${ZFS_VERSION}/zfs-${ZFS_VERSION}.tar.gz

# Extract source
echo "Extracting source..."
tar -xzf zfs-${ZFS_VERSION}.tar.gz
cd ${ZFS_SOURCE_DIR}

# Check if debian directory exists from upstream
if [ -d "debian" ]; then
    echo "Using upstream debian directory..."
    # Just update the changelog
    cat > debian/changelog << EOF
zfs-linux (${ZFS_VERSION}-1) unstable; urgency=medium

  * Local build of ZFS ${ZFS_VERSION}
  * Optimized for Meteor Lake with P-core AVX-512

 -- Local Build <root@localhost>  $(date -R)
EOF
else
    # Prepare Debian build files
    echo "Preparing Debian packaging..."
    echo "Creating debian directory..."
    mkdir -p debian
    
    # Basic control file
    cat > debian/control << 'EOF'
Source: zfs-linux
Section: contrib/kernel
Priority: optional
Maintainer: Local Build <root@localhost>
Build-Depends: debhelper-compat (= 13),
               dh-python,
               autoconf,
               automake,
               libtool,
               gawk,
               dkms,
               libblkid-dev,
               uuid-dev,
               libudev-dev,
               libssl-dev,
               zlib1g-dev,
               libaio-dev,
               libattr1-dev,
               libelf-dev,
               python3-all-dev,
               python3-cffi,
               libffi-dev,
               python3-setuptools,
               python3-packaging,
               libcurl4-openssl-dev,
               po-debconf
Standards-Version: 4.6.0
Homepage: https://github.com/openzfs/zfs

Package: zfsutils-linux
Architecture: any
Depends: ${shlibs:Depends}, ${misc:Depends}, ${python3:Depends}
Recommends: zfs-dkms
Description: OpenZFS filesystem utilities
 ZFS is a combined file system and logical volume manager designed by
 Sun Microsystems. This package provides the ZFS userland tools.

Package: zfs-dkms
Architecture: all
Depends: ${misc:Depends}, dkms (>= 2.3)
Description: OpenZFS filesystem kernel modules (DKMS)
 ZFS is a combined file system and logical volume manager designed by
 Sun Microsystems. This package provides the kernel modules using DKMS.

Package: libzfs4t64
Architecture: any
Depends: ${shlibs:Depends}, ${misc:Depends}
Description: OpenZFS library
 ZFS library for accessing ZFS filesystems programmatically.

Package: libzpool5t64
Architecture: any
Depends: ${shlibs:Depends}, ${misc:Depends}
Description: OpenZFS pool library
 ZFS pool library for accessing ZFS pools programmatically.

Package: libnvpair3t64
Architecture: any
Depends: ${shlibs:Depends}, ${misc:Depends}
Description: OpenZFS name-value pair library
 Library for manipulating name-value pairs used by ZFS.

Package: libuutil3t64
Architecture: any
Depends: ${shlibs:Depends}, ${misc:Depends}
Description: OpenZFS utility library
 Utility library used by ZFS tools.

Package: zfs-zed
Architecture: any
Depends: ${shlibs:Depends}, ${misc:Depends}, zfsutils-linux (= ${binary:Version})
Description: OpenZFS Event Daemon
 ZED (ZFS Event Daemon) monitors events generated by the ZFS kernel module.

Package: python3-pyzfs
Architecture: any
Depends: ${python3:Depends}, ${misc:Depends}, libzfs4t64 (= ${binary:Version})
Description: Python bindings for ZFS
 Python 3 bindings for programmatic access to ZFS.
EOF

    # Basic rules file
    cat > debian/rules << 'EOF'
#!/usr/bin/make -f

export DH_VERBOSE = 1
export DEB_BUILD_MAINT_OPTIONS = hardening=+all
export DEB_CFLAGS_MAINT_APPEND = -O2 -march=native -mtune=native
export DEB_CXXFLAGS_MAINT_APPEND = -O2 -march=native -mtune=native

%:
	dh $@ --with python3 --with dkms

override_dh_auto_configure:
	./autogen.sh
	dh_auto_configure -- \
		--prefix=/usr \
		--sysconfdir=/etc \
		--sbindir=/sbin \
		--libdir=/usr/lib/$(DEB_HOST_MULTIARCH) \
		--with-config=all \
		--enable-systemd \
		--enable-pyzfs \
		--with-systemdunitdir=/lib/systemd/system \
		--with-systemdpresetdir=/lib/systemd/system-preset \
		--with-systemdgeneratordir=/lib/systemd/system-generators

override_dh_auto_build:
	taskset -c 0-7 dh_auto_build -- -j8

override_dh_dkms:
	# Create DKMS configuration
	mkdir -p debian/zfs-dkms/usr/src/zfs-$(VERSION)
	cp -r module/* debian/zfs-dkms/usr/src/zfs-$(VERSION)/
	dh_dkms -pzfs-dkms

override_dh_python3:
	dh_python3 --no-ext-rename
EOF
    chmod +x debian/rules

    # Changelog
    cat > debian/changelog << EOF
zfs-linux (${ZFS_VERSION}-1) unstable; urgency=medium

  * Local build of ZFS ${ZFS_VERSION}
  * Optimized for Meteor Lake with P-core AVX-512

 -- Local Build <root@localhost>  $(date -R)
EOF

    # Copyright
    cat > debian/copyright << 'EOF'
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: zfs
Source: https://github.com/openzfs/zfs

Files: *
Copyright: 2001-2024 OpenZFS Contributors
License: CDDL-1.0
EOF

    # Don't create debian/compat - we use debhelper-compat in control file
fi

# Run autogen.sh first
echo "Running autogen.sh..."
./autogen.sh

# Build binary packages on P-cores
echo "Building binary packages on P-cores (0-7)..."
taskset -c 0-7 dpkg-buildpackage -us -uc -b -j8

# List generated packages
echo ""
echo "=== Generated Debian Packages ==="
ls -la ${BUILD_DIR}/*.deb

echo ""
echo "=== Installation Instructions ==="
echo "To install all packages:"
echo "cd ${BUILD_DIR}"
echo "sudo dpkg -i libzfs4t64_*.deb libzpool5t64_*.deb libnvpair3t64_*.deb libuutil3t64_*.deb"
echo "sudo dpkg -i zfsutils-linux_*.deb zfs-zed_*.deb zfs-dkms_*.deb"
echo "sudo dpkg -i python3-pyzfs_*.deb  # Optional Python bindings"
echo ""
echo "Or install all at once:"
echo "sudo dpkg -i ${BUILD_DIR}/*.deb"
echo "sudo apt --fix-broken install  # If needed for dependencies"