# ----------------------------------------------------------------------
#  Z-Forge Build Configuration – H730 Mini  •  version 2 (2025-06-19)
#  Notes:
#    • Switched base to Debian SID (unstable) for newest toolchain/kernel.
#    • ZFS pools default to zstd-6 compression (balanced ratio vs. CPU cost).
#    • Added optional hardening & observability hooks.
# ----------------------------------------------------------------------

builder_config:
  debian_release: sid          # ← changed from “bookworm”
  kernel_version: latest
  output_iso_name: zforge-h730mini-proxmox-v2.iso   # bumped minor version
  enable_debug: true
  workspace_path: /tmp/zforge_workspace
  cache_packages: true
  # --- new knobs ------------------------------------------------------
  gpg_verify: true             # verify downloaded debs/ISOs
  reproducible_build: true     # fix timestamps/env for bit-repro builds
  log_verbosity: 2             # 0=quiet 1=normal 2=debug

proxmox_config:
  version: latest
  minimal_install: true
  include_packages:
    # Core Proxmox stack
    - proxmox-ve
    - pve-kernel-6.8
    - zfs-dkms
    - zfsutils-linux
    - pve-zsync
    # H730 Mini / hardware mgmt
    - ipmitool
    - openipmi
    - lm-sensors
    - nvme-cli
    - megacli
    - megactl
    - megaraid-status
    - srvadmin-all            # Dell OMSA for sensor / RAID telemetry
    # Observability & burn-in
    - snmp
    - ethtool
    - fio
    - smartmontools
    - stress-ng               # (new) synthetic load generator
    - sosreport               # (new) capture full HW/SW state for tickets

zfs_config:
  version: latest
  build_from_source: true      # ensures SID toolchain is used
  enable_encryption: true
  default_compression: zstd-6  # ← changed from lz4 → zstd-6
  arc_max_size: "16G"
  prefetch_disable: false
  zio_delay_max: 5000
  # --- new: optional pool-wide settings -------------------------------
  ashift: 12                   # 4 KiB sector alignment (SSD-friendly)
  autotrim: on                 # SSD wear-level; OK on H730 BBU cache

bootloader_config:
  primary: zfsbootmenu
  enable_opencore: true
  enable_two_stage: true
  opencore_drivers:
    - NvmExpressDxe.efi
    - OpenRuntime.efi
  nvme_pcie_path: "PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)"
  uefi_mode: true
  # --- secure-boot stub (optional) ------------------------------------
  shim_secureboot: false       # flip to true if you sign zfsbootmenu

dracut_config:
  modules:
    - zfs
    - systemd
    - network
  compress: zstd               # algorithm
  compress_level: 6            # ← explicit level to mirror zstd-6
  hostonly: true
  kernel_cmdline: |
    root=zfs:AUTO
    console=tty0
    console=ttyS0,115200n8
    mitigations=auto,nosmt
    ipv6.disable=1            # (optional) cut attack surface if unused
  extra_drivers:
    - nvme
    - megaraid_sas
    - mpt3sas
    - mptbase
    - mptscsih
    - bnx2x
    - igb
    - ixgbe
    - i40e
    - rng_core              # (new) HW RNG for faster keygen/entropy

post_install_scripts:
  # empty list → populate with bespoke hardening or agent deploy steps
  - scripts/99_finalize.sh

modules:
  - name: WorkspaceSetup
    enabled: true
  - name: Debootstrap
    enabled: true
  - name: KernelAcquisition
    enabled: true
  - name: ZFSBuild
    enabled: true
  - name: DracutConfig
    enabled: true
  - name: ProxmoxIntegration
    enabled: true
  - name: LiveEnvironment
    enabled: true
  - name: CalamaresIntegration
    enabled: true
  - name: ISOGeneration
    enabled: true
  # --- new modular hooks ----------------------------------------------
  - name: SecurityHardening
    enabled: true
  - name: Telemetry
    enabled: true
