#!/usr/bin/env python3
"""
ZFS Pool Configuration Module for Z-FORGE
Supports multiple pools with different RAID-Z levels for OS and storage
"""

import os
import subprocess
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Any
import logging

class ZfsPoolConfig:
    """Handles advanced ZFS pool configuration with multiple pools"""
    
    def __init__(self, workspace: Path, config: Dict):
        self.workspace = workspace
        self.config = config
        self.logger = logging.getLogger(__name__)
        self.pool_configs = []
        
    def execute(self, resume_data: Optional[Dict] = None, lockfile: Optional[Any] = None) -> Dict:
        """
        Configure multiple ZFS pools based on configuration
        
        Args:
            resume_data: Resume data dictionary
            lockfile: Lock file object
            
        Returns:
            Status dictionary
        """
        try:
            self.logger.info("Configuring ZFS pools...")
            
            # Get pool configurations
            pool_config = self.config.get('zfs_pool_config', {})
            
            # Configure OS pool (root pool)
            os_pool = pool_config.get('os_pool', {
                'name': 'rpool',
                'type': 'mirror',
                'devices': [],  # Will be filled by installer
                'encryption': True,
                'compression': 'zstd-3',  # Will be dynamically optimized
                'ashift': 12
            })
            
            # Configure storage pools
            storage_pools = pool_config.get('storage_pools', [])
            
            # Generate pool creation scripts
            self._create_os_pool_script(os_pool)
            
            for storage_pool in storage_pools:
                self._create_storage_pool_script(storage_pool)
            
            # Create combined setup script
            self._create_master_setup_script(os_pool, storage_pools)
            
            # Create dataset layout configurations
            self._create_dataset_layouts(os_pool, storage_pools)
            
            return {
                'status': 'success',
                'os_pool': os_pool['name'],
                'storage_pools': [p['name'] for p in storage_pools],
                'features': {
                    'multiple_pools': True,
                    'raid_z_support': True,
                    'encryption_per_pool': True,
                    'dataset_layouts': True
                }
            }
            
        except Exception as e:
            self.logger.error(f"Failed to configure ZFS pools: {e}")
            return {
                'status': 'error',
                'error': str(e),
                'module': self.__class__.__name__
            }
    
    def _create_os_pool_script(self, pool_config: Dict):
        """Create script for OS pool creation"""
        self.logger.info(f"Creating OS pool script for {pool_config['name']}...")
        
        script_content = f"""#!/bin/bash
# OS Pool Creation Script
# Generated by Z-FORGE

set -e

POOL_NAME="{pool_config['name']}"
POOL_TYPE="{pool_config['type']}"
ENCRYPTION={str(pool_config.get('encryption', True)).lower()}
COMPRESSION="{pool_config.get('compression', 'lz4')}"
ASHIFT={pool_config.get('ashift', 12)}

echo "Creating OS pool: $POOL_NAME"

# Function to create pool based on type
create_pool() {{
    local devices=("$@")
    local create_cmd="zpool create -f"
    
    # Add pool options
    create_cmd="$create_cmd -o ashift=$ASHIFT"
    create_cmd="$create_cmd -o autotrim=on"
    create_cmd="$create_cmd -o compatibility=openzfs-2.1-linux"
    
    # Add dataset options
    create_cmd="$create_cmd -O acltype=posixacl"
    create_cmd="$create_cmd -O compression=$COMPRESSION"
    create_cmd="$create_cmd -O dnodesize=auto"
    create_cmd="$create_cmd -O normalization=formD"
    create_cmd="$create_cmd -O relatime=on"
    create_cmd="$create_cmd -O xattr=sa"
    
    # Add encryption if enabled
    if [ "$ENCRYPTION" = "true" ]; then
        create_cmd="$create_cmd -O encryption=aes-256-gcm"
        create_cmd="$create_cmd -O keylocation=file:///etc/zfs/$POOL_NAME.key"
        create_cmd="$create_cmd -O keyformat=raw"
    fi
    
    # Add mountpoint
    create_cmd="$create_cmd -O mountpoint=none"
    
    # Add root mount
    create_cmd="$create_cmd -R /mnt"
    
    # Add pool name
    create_cmd="$create_cmd $POOL_NAME"
    
    # Add vdev configuration based on type
    case $POOL_TYPE in
        mirror)
            create_cmd="$create_cmd mirror ${{devices[@]}}"
            ;;
        raidz|raidz1)
            create_cmd="$create_cmd raidz1 ${{devices[@]}}"
            ;;
        raidz2)
            create_cmd="$create_cmd raidz2 ${{devices[@]}}"
            ;;
        raidz3)
            create_cmd="$create_cmd raidz3 ${{devices[@]}}"
            ;;
        stripe|*)
            create_cmd="$create_cmd ${{devices[@]}}"
            ;;
    esac
    
    echo "Executing: $create_cmd"
    eval $create_cmd
}}

# Create encryption key if needed
if [ "$ENCRYPTION" = "true" ]; then
    echo "Generating encryption key..."
    mkdir -p /etc/zfs
    dd if=/dev/urandom of=/etc/zfs/$POOL_NAME.key bs=32 count=1
    chmod 400 /etc/zfs/$POOL_NAME.key
fi

# Get devices from command line or use defaults
if [ $# -eq 0 ]; then
    echo "Usage: $0 <device1> [device2] ..."
    exit 1
fi

# Create the pool
create_pool "$@"

# Create root dataset structure
echo "Creating OS datasets..."
zfs create -o mountpoint=none $POOL_NAME/ROOT
zfs create -o mountpoint=/ $POOL_NAME/ROOT/debian
zfs create -o mountpoint=/home $POOL_NAME/home
zfs create -o mountpoint=/var $POOL_NAME/var
zfs create -o mountpoint=/var/lib $POOL_NAME/var/lib
zfs create -o mountpoint=/var/log $POOL_NAME/var/log
zfs create -o mountpoint=/var/spool $POOL_NAME/var/spool
zfs create -o mountpoint=/var/tmp -o com.sun:auto-snapshot=false $POOL_NAME/var/tmp
chmod 1777 /mnt/var/tmp

# Create container datasets for Proxmox
zfs create -o mountpoint=/var/lib/vz $POOL_NAME/var/lib/vz
zfs create $POOL_NAME/var/lib/vz/images
zfs create $POOL_NAME/var/lib/vz/private

echo "OS pool $POOL_NAME created successfully!"
"""
        
        script_path = self.workspace / f"create_os_pool_{pool_config['name']}.sh"
        with open(script_path, 'w') as f:
            f.write(script_content)
        os.chmod(script_path, 0o755)
    
    def _create_storage_pool_script(self, pool_config: Dict):
        """Create script for storage pool creation"""
        self.logger.info(f"Creating storage pool script for {pool_config['name']}...")
        
        raid_levels = {
            'stripe': '',
            'mirror': 'mirror',
            'raidz': 'raidz1',
            'raidz1': 'raidz1',
            'raidz2': 'raidz2',
            'raidz3': 'raidz3'
        }
        
        script_content = f"""#!/bin/bash
# Storage Pool Creation Script: {pool_config['name']}
# Generated by Z-FORGE

set -e

POOL_NAME="{pool_config['name']}"
POOL_TYPE="{pool_config['type']}"
RAID_CMD="{raid_levels.get(pool_config['type'], '')}"
ENCRYPTION={str(pool_config.get('encryption', False)).lower()}
COMPRESSION="{pool_config.get('compression', 'lz4')}"
ASHIFT={pool_config.get('ashift', 12)}
RECORDSIZE="{pool_config.get('recordsize', '128K')}"

echo "Creating storage pool: $POOL_NAME"

# Create encryption key if needed
if [ "$ENCRYPTION" = "true" ]; then
    echo "Generating encryption key..."
    mkdir -p /etc/zfs
    dd if=/dev/urandom of=/etc/zfs/$POOL_NAME.key bs=32 count=1
    chmod 400 /etc/zfs/$POOL_NAME.key
fi

# Create pool
echo "Creating ZFS pool..."
zpool create -f \\
    -o ashift=$ASHIFT \\
    -o autotrim=on \\
    -o compatibility=openzfs-2.1-linux \\
    -O acltype=posixacl \\
    -O compression=$COMPRESSION \\
    -O dnodesize=auto \\
    -O normalization=formD \\
    -O relatime=on \\
    -O xattr=sa \\
    -O recordsize=$RECORDSIZE \\
    $([ "$ENCRYPTION" = "true" ] && echo "-O encryption=aes-256-gcm -O keylocation=file:///etc/zfs/$POOL_NAME.key -O keyformat=raw") \\
    -O mountpoint=/{pool_config.get('mountpoint', pool_config['name'])} \\
    $POOL_NAME \\
    $RAID_CMD $@

# Create datasets based on purpose
PURPOSE="{pool_config.get('purpose', 'general')}"

case $PURPOSE in
    vm_storage)
        echo "Creating VM storage datasets..."
        zfs create -o recordsize=64K $POOL_NAME/vm-disks
        zfs create -o recordsize=1M $POOL_NAME/vm-backups
        zfs create $POOL_NAME/templates
        zfs create $POOL_NAME/iso
        ;;
        
    backup)
        echo "Creating backup datasets..."
        zfs create -o recordsize=1M $POOL_NAME/backups
        zfs create $POOL_NAME/backups/daily
        zfs create $POOL_NAME/backups/weekly
        zfs create $POOL_NAME/backups/monthly
        zfs create $POOL_NAME/archives
        ;;
        
    media)
        echo "Creating media storage datasets..."
        zfs create -o recordsize=1M $POOL_NAME/media
        zfs create $POOL_NAME/media/videos
        zfs create $POOL_NAME/media/music
        zfs create $POOL_NAME/media/photos
        zfs create $POOL_NAME/media/documents
        ;;
        
    database)
        echo "Creating database datasets..."
        zfs create -o recordsize=8K -o primarycache=metadata $POOL_NAME/postgres
        zfs create -o recordsize=16K $POOL_NAME/mysql
        zfs create -o recordsize=8K $POOL_NAME/mongodb
        ;;
        
    *)
        echo "Creating general purpose datasets..."
        zfs create $POOL_NAME/data
        zfs create $POOL_NAME/shares
        ;;
esac

# Set up automatic snapshots
echo "Configuring automatic snapshots..."
for interval in frequent hourly daily weekly monthly; do
    zfs set com.sun:auto-snapshot:$interval=true $POOL_NAME
done

echo "Storage pool $POOL_NAME created successfully!"
"""
        
        script_path = self.workspace / f"create_storage_pool_{pool_config['name']}.sh"
        with open(script_path, 'w') as f:
            f.write(script_content)
        os.chmod(script_path, 0o755)
    
    def _create_master_setup_script(self, os_pool: Dict, storage_pools: List[Dict]):
        """Create master script that sets up all pools"""
        self.logger.info("Creating master pool setup script...")
        
        script_content = """#!/bin/bash
# Master ZFS Pool Setup Script
# Generated by Z-FORGE

set -e

echo "=== Z-FORGE ZFS Pool Configuration ==="
echo ""

# Function to check if pool exists
pool_exists() {
    zpool list -H "$1" >/dev/null 2>&1
}

# OS Pool Setup
OS_POOL="%s"
if pool_exists "$OS_POOL"; then
    echo "OS pool $OS_POOL already exists, skipping..."
else
    echo "Setting up OS pool: $OS_POOL"
    # Call OS pool creation script with devices
    # This would be populated by the installer
fi

# Storage Pool Setup
""" % os_pool['name']
        
        for pool in storage_pools:
            script_content += f"""
# {pool['name']} Pool
POOL_{pool['name'].upper()}="{pool['name']}"
if pool_exists "$POOL_{pool['name'].upper()}"; then
    echo "Storage pool {pool['name']} already exists, skipping..."
else
    echo "Setting up storage pool: {pool['name']}"
    echo "Purpose: {pool.get('purpose', 'general')}"
    echo "Type: {pool['type']}"
    echo "Please run: ./create_storage_pool_{pool['name']}.sh <devices...>"
fi
"""
        
        script_content += """
# Set up ZED (ZFS Event Daemon)
echo "Configuring ZED..."
systemctl enable zfs-zed
systemctl start zfs-zed

# Configure scrub timers
echo "Setting up scrub schedule..."
cat > /etc/systemd/system/zfs-scrub@.timer <<EOF
[Unit]
Description=Monthly zpool scrub for %i

[Timer]
OnCalendar=monthly
Persistent=true

[Install]
WantedBy=timers.target
EOF

cat > /etc/systemd/system/zfs-scrub@.service <<EOF
[Unit]
Description=zpool scrub for %i

[Service]
Type=oneshot
ExecStart=/usr/sbin/zpool scrub %i
EOF

# Enable scrub for all pools
for pool in $(zpool list -H -o name); do
    systemctl enable zfs-scrub@$pool.timer
done

echo ""
echo "=== ZFS Pool Setup Complete ==="
echo ""
echo "Active pools:"
zpool list
echo ""
echo "To import pools after reboot:"
echo "  zpool import -a"
echo ""
"""
        
        script_path = self.workspace / "setup_all_pools.sh"
        with open(script_path, 'w') as f:
            f.write(script_content)
        os.chmod(script_path, 0o755)
    
    def _create_dataset_layouts(self, os_pool: Dict, storage_pools: List[Dict]):
        """Create dataset layout documentation"""
        self.logger.info("Creating dataset layout documentation...")
        
        layout = {
            'os_pool': {
                'name': os_pool['name'],
                'purpose': 'Operating System',
                'datasets': {
                    f"{os_pool['name']}/ROOT": "Root container (no mount)",
                    f"{os_pool['name']}/ROOT/debian": "Main OS (/)",
                    f"{os_pool['name']}/home": "User home directories",
                    f"{os_pool['name']}/var": "Variable data",
                    f"{os_pool['name']}/var/lib/vz": "Proxmox containers/VMs"
                }
            },
            'storage_pools': []
        }
        
        for pool in storage_pools:
            pool_layout = {
                'name': pool['name'],
                'purpose': pool.get('purpose', 'general'),
                'type': pool['type'],
                'datasets': self._get_dataset_layout_for_purpose(
                    pool['name'], 
                    pool.get('purpose', 'general')
                )
            }
            layout['storage_pools'].append(pool_layout)
        
        # Save layout
        layout_path = self.workspace / "zfs_dataset_layout.json"
        with open(layout_path, 'w') as f:
            json.dump(layout, f, indent=2)
        
        # Create human-readable documentation
        doc_content = """# ZFS Dataset Layout

## OS Pool: %s
- **Purpose**: Operating System and core services
- **Type**: %s
- **Encryption**: %s

### Datasets:
""" % (os_pool['name'], os_pool['type'], os_pool.get('encryption', True))
        
        for dataset, purpose in layout['os_pool']['datasets'].items():
            doc_content += f"- `{dataset}`: {purpose}\n"
        
        doc_content += "\n## Storage Pools\n\n"
        
        for pool in layout['storage_pools']:
            doc_content += f"""### {pool['name']}
- **Purpose**: {pool['purpose']}
- **Type**: {pool['type']}

#### Datasets:
"""
            for dataset, purpose in pool['datasets'].items():
                doc_content += f"- `{dataset}`: {purpose}\n"
            doc_content += "\n"
        
        doc_path = self.workspace / "ZFS_DATASET_LAYOUT.md"
        with open(doc_path, 'w') as f:
            f.write(doc_content)
    
    def _get_dataset_layout_for_purpose(self, pool_name: str, purpose: str) -> Dict[str, str]:
        """Get recommended dataset layout based on purpose"""
        layouts = {
            'vm_storage': {
                f"{pool_name}/vm-disks": "Virtual machine disk images (64K recordsize)",
                f"{pool_name}/vm-backups": "VM backup files (1M recordsize)",
                f"{pool_name}/templates": "VM templates",
                f"{pool_name}/iso": "ISO images"
            },
            'backup': {
                f"{pool_name}/backups": "Main backup directory",
                f"{pool_name}/backups/daily": "Daily backups",
                f"{pool_name}/backups/weekly": "Weekly backups",
                f"{pool_name}/backups/monthly": "Monthly backups",
                f"{pool_name}/archives": "Long-term archives"
            },
            'media': {
                f"{pool_name}/media": "Media root",
                f"{pool_name}/media/videos": "Video files (1M recordsize)",
                f"{pool_name}/media/music": "Audio files",
                f"{pool_name}/media/photos": "Photo files",
                f"{pool_name}/media/documents": "Documents"
            },
            'database': {
                f"{pool_name}/postgres": "PostgreSQL data (8K recordsize)",
                f"{pool_name}/mysql": "MySQL data (16K recordsize)",
                f"{pool_name}/mongodb": "MongoDB data (8K recordsize)"
            },
            'general': {
                f"{pool_name}/data": "General data storage",
                f"{pool_name}/shares": "Network shares"
            }
        }
        
        return layouts.get(purpose, layouts['general'])