# Z-Forge Build Configuration for PowerEdge R420 with NVMe
builder_config:
  debian_release: bookworm
  kernel_version: latest
  output_iso_name: zforge-r420-proxmox-v3.iso
  enable_debug: true
  workspace_path: /tmp/zforge_workspace
  cache_packages: true

proxmox_config:
  version: latest
  minimal_install: true
  include_packages:
    - proxmox-ve
    - pve-kernel-6.8
    - zfs-dkms
    - zfsutils-linux
    - pve-zsync
    # Dell PowerEdge R420 specific packages
    - ipmitool
    - openipmi
    - lm-sensors
    - nvme-cli
    - megacli
    - megactl
    - megaraid-status
    - srvadmin-all
    - snmp
    - ethtool

zfs_config:
  version: latest
  build_from_source: true
  enable_encryption: true
  default_compression: lz4
  # R420 RAM optimization
  arc_max_size: "4G"
  # Server optimizations
  prefetch_disable: true
  zio_delay_max: 10000

bootloader_config:
  primary: zfsbootmenu
  # Enable two-stage boot for R420 with NVMe
  enable_opencore: true
  enable_two_stage: true
  opencore_drivers:
    - NvmExpressDxe.efi
    - OpenRuntime.efi
  # Dell PowerEdge R420 PCIe path configuration
  nvme_pcie_path: "PciRoot(0x0)/Pci(0x2,0x0)/Pci(0x0,0x0)"
  # Legacy BIOS mode for R420
  uefi_mode: false

dracut_config:
  modules:
    - zfs
    - systemd
    - network
  compress: zstd
  hostonly: true
  # Add serial console support for R420
  kernel_cmdline: "root=zfs:AUTO console=tty0 console=ttyS0,115200n8"
  extra_drivers:
    - nvme
    # Dell PERC RAID controller drivers
    - megaraid_sas
    - mpt3sas
    - mptbase
    - mptscsih
    # Network drivers for Dell PowerEdge R420
    - bnx2
    - igb
    - e1000e

# Dell PowerEdge R420 specific configuration
dell_r420_config:
  enable_serial_console: true
  serial_port: "ttyS0"
  serial_speed: 115200
  enable_idrac: true
  # IPMI configuration
  ipmi_settings:
    enable_sol: true
    sol_speed: 115200
  # Hardware RAID configuration
  raid_monitoring: true
  # NVMe optimization
  nvme_settings:
    io_timeout: 4294967295
    max_host_mem_size_mb: 256
    scheduler: "none"
    read_ahead_kb: 2048
    nr_requests: 1024
  # CPU optimization
  cpu_governor: "performance"

# Include Dell R420 specific post-install scripts
post_install_scripts:
  - config/r420/r420_post_install.sh
  - config/r420/r420_nvme_tune.sh

modules:
  - name: WorkspaceSetup
    enabled: true
  - name: Debootstrap
    enabled: true
  - name: KernelAcquisition
    enabled: true
  - name: ZFSBuild
    enabled: true
  - name: DracutConfig
    enabled: true
  - name: ProxmoxIntegration
    enabled: true
  - name: LiveEnvironment
    enabled: true
  - name: CalamaresIntegration
    enabled: true
  - name: DellR420Optimize
    enabled: true
  - name: ISOGeneration
    enabled: true
