# ----------------------------------------------------------------------
#  Z-Forge Build Configuration – Dell S130 (SW-RAID)   • 2025-06-19 v2
#  Key deltas vs. v1
#    • Debian sid  ➜ newest mdraid/ZFS stacks
#    • ZFS pool defaults: zstd-6, ashift=12, autotrim=on
#    • Explicit mdraid early-assembly in Dracut
#    • ARC capped at 4 GiB (typical 32 GiB entry servers)
#    • Extra burn-in / diagnostics packages
# ----------------------------------------------------------------------

builder_config:
  debian_release: sid
  kernel_version: latest
  output_iso_name: zforge-s130-proxmox-v2.iso
  enable_debug: true
  workspace_path: /tmp/zforge_workspace
  cache_packages: true
  gpg_verify: true
  reproducible_build: true
  log_verbosity: 2            # 0=quiet 1=normal 2=debug

proxmox_config:
  version: latest
  minimal_install: true
  include_packages:
    # Core Proxmox
    - proxmox-ve
    - pve-kernel-6.8
    - zfs-dkms
    - zfsutils-linux
    - pve-zsync
    # S130 SW-RAID & platform tools
    - mdadm
    - ipmitool
    - openipmi
    - lm-sensors
    - nvme-cli                # keep — some S130 boxes ship with NVMe sleds
    - srvadmin-all
    # Observability / burn-in
    - snmp
    - ethtool
    - fio
    - smartmontools
    - stress-ng
    - sosreport

zfs_config:
  version: latest
  build_from_source: true
  enable_encryption: true
  default_compression: zstd-6
  arc_max_size: "4G"          # S130 boxes often ≤32 GiB RAM
  prefetch_disable: false
  zio_delay_max: 5000
  ashift: 12
  autotrim: on

bootloader_config:
  primary: zfsbootmenu
  enable_opencore: true
  enable_two_stage: true
  opencore_drivers:
    - NvmExpressDxe.efi
    - OpenRuntime.efi
  nvme_pcie_path: "PciRoot(0x0)/Pci(0x3,0x0)/Pci(0x0,0x0)"   # verify on S130 chassis
  uefi_mode: true
  shim_secureboot: false

dracut_config:
  modules:
    - zfs
    - mdraid                 # **must** precede zfs import if root on MD
    - systemd
    - network
  compress: zstd
  compress_level: 6
  hostonly: true
  kernel_cmdline: |
    rd.auto
    rd.md=0                  # auto-assemble all mdraid sets
    root=zfs:AUTO
    console=tty0
    console=ttyS0,115200n8
    mitigations=auto,nosmt
    ipv6.disable=1
  extra_drivers:
    - nvme
    - bnx2x
    - igb
    - ixgbe
    - i40e
    - ahci                  # explicit for SATA SW-RAID
    - rng_core

post_install_scripts:
  - scripts/99_finalize.sh     # generic finisher (adds mdadm moni-tor)

modules:
  - name: WorkspaceSetup
    enabled: true
  - name: Debootstrap
    enabled: true
  - name: KernelAcquisition
    enabled: true
  - name: ZFSBuild
    enabled: true
  - name: DracutConfig
    enabled: true
  - name: ProxmoxIntegration
    enabled: true
  - name: LiveEnvironment
    enabled: true
  - name: CalamaresIntegration
    enabled: true
  - name: ISOGeneration
    enabled: true
  - name: SecurityHardening
    enabled: true
  - name: Telemetry
    enabled: true
